// Generated by Ludicord. Changes will be replaced by ludicord dev or ludicord build.
import "ludicord/navigation";

declare module "ludicord/navigation" {
  interface LudicordRouteRegistry {
    readonly prefix: "/";
    readonly pagePattern: "/";
    readonly pageParams: {
      readonly "/": Readonly<Record<string, never>>;
    };
    readonly embed: "game";
    readonly embedPattern: "game";
    readonly embedsByPrefix: {
      readonly "/": "game";
    };
    readonly api: never;
    readonly websocket: "/ws/adventure";
    readonly embedParams: {
      readonly "game": Readonly<Record<string, never>>;
    };
    readonly apiParams: {

    };
    readonly websocketParams: {
      readonly "/ws/adventure": Readonly<Record<string, never>>;
    };
    readonly config: {
      readonly defaultEmbed: "game";
      readonly outsideDiscord: "allow";
      readonly authRequired: true;
      readonly strictMode: true;
      readonly clientAssetWarningLimit: 2000000;
    };
  }
}
